# Generated by Django 3.0.8 on 2020-09-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('img_path', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Vtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=255, null=True)),
                ('chara_img', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=20, null=True)),
                ('color', models.CharField(default='#ffffff', max_length=8)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vradio_api.Type')),
            ],
            options={
                'db_table': 'vtubers',
            },
        ),
    ]
